name: "Platform Application Deploy"

on:
  push:
    branches: [ "master" ]
    paths:
      - 'platform/**'
      - 'modules/**'
      - 'config.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'platform/**'
      - 'modules/**'

jobs:
  terraform:
    name: "Terraform Platform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./platform

      - name: Terraform Init
        run: terraform init -backend-config=backend.hcl
        working-directory: ./platform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./platform

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        working-directory: ./platform
